
# syntax=docker/dockerfile:1

# docker build -t flask-ubuntu -f Dockerfile.ubuntu .
# docker run -d -p 5000:5000 flask-ubuntu

FROM ubuntu:20.04

ENV TERM linux
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y
RUN apt-get install -y python3 python3-pip

RUN pip3 install flask

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY app.py app.py

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0" ]

